// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnLtUp4xjY2iI3zN7JDAdK4hJ_o2HEgD4',
    appId: '1:3091897365:web:b5827cf0c6205f4fdf821c',
    messagingSenderId: '3091897365',
    projectId: 'backend-chargeit-test',
    authDomain: 'backend-chargeit-test.firebaseapp.com',
    storageBucket: 'backend-chargeit-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ5RFYPNSJAb76n06Yn9fKBcZCv0m8wTA',
    appId: '1:3091897365:android:531386e35f130b7bdf821c',
    messagingSenderId: '3091897365',
    projectId: 'backend-chargeit-test',
    storageBucket: 'backend-chargeit-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKykHWroHsW3OSCla0Mg-7hut0RO2AI1s',
    appId: '1:3091897365:ios:b85ec3732ea20deddf821c',
    messagingSenderId: '3091897365',
    projectId: 'backend-chargeit-test',
    storageBucket: 'backend-chargeit-test.firebasestorage.app',
    iosBundleId: 'com.backend.chargit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKykHWroHsW3OSCla0Mg-7hut0RO2AI1s',
    appId: '1:3091897365:ios:b85ec3732ea20deddf821c',
    messagingSenderId: '3091897365',
    projectId: 'backend-chargeit-test',
    storageBucket: 'backend-chargeit-test.firebasestorage.app',
    iosBundleId: 'com.backend.chargit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnLtUp4xjY2iI3zN7JDAdK4hJ_o2HEgD4',
    appId: '1:3091897365:web:c6f7ae2048a13191df821c',
    messagingSenderId: '3091897365',
    projectId: 'backend-chargeit-test',
    authDomain: 'backend-chargeit-test.firebaseapp.com',
    storageBucket: 'backend-chargeit-test.firebasestorage.app',
  );
}